"""add new column to books

Revision ID: a059e587fbae
Revises: 0bd8e7a0fee2
Create Date: 2022-06-25 18:21:53.934375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a059e587fbae'
down_revision = '0bd8e7a0fee2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('views_stat', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'views_stat')
    # ### end Alembic commands ###
